### ISSUE TITLE
404 seconde connexion

### ISSUE THREAD

**Issue by abernier** [abernier/cinetek-www-issues#2]
A la seconde connection, il y a des bugs sur les liens fournis dans les mails. Page 404. Ce n'est pas très fluide. Peux-tu me redonner le déroulé type stp pour comprendre?

**Comment by abernier** [comment]
@Celine,

Je n'ai pas reproduit mais j'ai simplifié : il n'y a maintenant qu'un seul email envoyé = celui pour la connexion

Je te laisse vérifier que c'est maintenant ok, merci

**Comment by abernier** [comment]
@celkin75 je te laisse fermer le ticket si ok pour toi, merci

**Comment by celkin75** [comment]
ok pour moi merci
