### ISSUE TITLE
bonne réponse

### ISSUE THREAD

**Issue by abernier** [abernier/cinetek-www-issues#3]
Sur mobile, à la 2nde parte, la page score est étrange : seulement une affiche apparaît. On me dit que c'est une bonne réponse alors que j'ai mal répondu...

**Comment by abernier** [comment]
@Celine,

Je ne suis pas sûr d'avoir compris, peux-tu détailler les étapes pour reproduire ?

Merci

**Comment by abernier** [comment]
@celkin75 bon maintenant avec la derniere version ? je te laisse fermer le ticket si ok, merci

**Comment by celkin75** [comment]
ok pour moi merci
