### ISSUE TITLE
visuel partage facebook

### ISSUE THREAD

**Issue by abernier** [abernier/cinetek-www-issues#6]
Quand on partage sur Facebook, le visuel est coupé. Doit-on te relivrer l'image ou peux-tu la recaler?

**Comment by abernier** [comment]
oui il faudrait la relivrer en respectant le ratio recommandé par facebook : 1200x630 px merci

**Comment by celkin75** [comment]
voici le visuel redimensionné
merci
![post-fb-cinetek-good](https://user-images.githubusercontent.com/37368631/37408973-84fb0468-279d-11e8-8e2a-a1c0daf55ee1.jpg)
![post-fb-cinetek-good](https://user-images.githubusercontent.com/37368631/37409001-91826c94-279d-11e8-914d-d6fcce7472c7.jpg)

**Comment by celkin75** [comment]
désolée je l'ai mis 2 fois

**Comment by abernier** [comment]
ok, je fais la modif et te dis une fois en ligne
