### ISSUE TITLE
50 affiches + liens

### ISSUE THREAD

**Issue by abernier** [abernier/cinetek-www-issues#7]
Quand pourra-t-on mettre les 50 affiches ?
Quand doit-on te fournir les liens vers les films ?

**Comment by abernier** [comment]
Je mettrai à jour les 50 affiches dès que vous aurez pu me transmettre les liens.

**Comment by celkin75** [comment]
voici le doc mis à jour avec les liens vers les films:
https://docs.google.com/spreadsheets/d/1Gl0E4fegHCRKFQHiS_LqdN_F0xkfa5yTH4NT1tBcZYw/edit?ts=5aa93804#gid=0
attention deux films ont changé de titre : en français au lieu de l'anglais (ils sont en rouge)

merci

**Comment by abernier** [comment]
bien recu je ferai la mise a jour et te dirai une fois en ligne

**Comment by abernier** [comment]
https://docs.google.com/spreadsheets/d/1Go_JHkEyo5wBjS9O2sR8GpXkIW4oSbKmCG8XYN8w_3Y/edit#gid=0
