### ISSUE TITLE
partage Facebook sur mobile

### ISSUE THREAD

**Issue by celkin75** [abernier/cinetek-www-issues#9]
Est-ce qu'il est possible de le partager également via l'appli Facebook ? sur mon iphone, il ne me propose pas le partage de cette façon-là, il faut que je me connecte à mon compte via safari (alors que sur téléphone on est par défaut bien souvent connectés via l'appli)
merci

**Comment by abernier** [comment]
Ce n'est pas possible, il s'agit du partage standard web par URL via les tags OG Facebook standard
